# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7478d58f3a606ac6ad4154726ae48f05569c5a6f17a844fc0c3b46badc68070408aacfc1ae81e585e98de4f99c8768c9cf6608c80da088d1c777c584dadc3622

test:
  secret_key_base: 48893d5636f48cd95cd8dd6a0378306d95777882bd561dd1e76013bfe306e8ba5a4e48a5c972dd998eab57a5105226279ace91fdfe682f4305cf641aa466a410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
